name: WIP Build & Deploy

on:
  workflow_run:
    workflows: ["PR → WIP CI (Before Merge)"]   # 🔥 pipeline name
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    # ✅ run only if CI passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      # Checkout correct commit
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install deps
      - name: Install Dependencies
        run: npm install

      # Build app
      - name: Build App
        run: npm run build

      # Deploy (mock)
      - name: Deploy
        run: echo "🚀 Deploy triggered after CI success"

      - name: Done
        run: echo "✅ Deployment successful"
     
      - name: Build Docker Image
        run: |
          docker build -t demo-ci-app:${{ github.sha }} .

      # 🧪 Docker Run Test (optional but best practice)
      - name: Run Container Test
        run: |
          docker run -d -p 3000:3000 --name test-container demo-ci-app:${{ github.sha }}
          sleep 5
          docker ps
          docker stop test-container

     
     
     
        # 🐳 Build Docker image
 #     - name: Build Docker Image
 #       run: |
 #         IMAGE_NAME=demo-app
 #         docker build -t $IMAGE_NAME:${{ github.sha }} .

      # 🔐 Scan Docker image (Trivy)
 #     - name: Trivy Image Scan
 #       uses: aquasecurity/trivy-action@master
 #       with:
 #         image-ref: demo-app:${{ github.sha }}
 #      continue-on-error: true   # for R&D

      # 🧠 Map branch → environment
 #     - name: Map Environment
 #       id: env
 #       run: |
 #         BRANCH=${GITHUB_REF#refs/heads/}


 #         if [[ $BRANCH == *"team1"* ]]; then
  #          echo "env=qa-team1" >> $GITHUB_OUTPUT
   #       elif [[ $BRANCH == *"team2"* ]]; then
    #        echo "env=qa-team2" >> $GITHUB_OUTPUT
     #     elif [[ $BRANCH == *"team3"* ]]; then
      #      echo "env=qa-team3" >> $GITHUB_OUTPUT
       #   else
        #    echo "env=qa-default" >> $GITHUB_OUTPUT
         # fi

      # 🚀 Deploy (mock for now)
#      - name: Deploy to Environment
 #       run: |
  #        echo "Deploying to ${{ steps.env.outputs.env }}"
   #       echo "Image: demo-app:${{ github.sha }}"

      # 📢 Notification (optional)
      - name: Deployment Success
        run: |
          echo "✅ Deployment successful to ${{ steps.env.outputs.env }}"

